version: '3.8'

services:
  fastapi-app:
    build: ./backend
    ports:
      - "8001:8001"
    networks:
      - keploy-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  keploy-network:
    driver: bridge